<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-6ERC4JE" failures="4" tests="10" name="Test" time="0.453" errors="0" timestamp="2023-08-29T01:54:26 IST">
  <testcase classname="Dwopractice1.NewTest" name="testCase1" time="0.016"/>
  <testcase classname="Dwopractice1.NewTest" name="testCase2" time="0.008"/>
  <testcase classname="Dwopractice1.NewTest" name="testCase3" time="0.008"/>
  <testcase classname="Dwopractice1.NewTest" name="testCase4" time="0.005"/>
  <testcase classname="Dwopractice1.NewTest" name="testCase5" time="0.028">
    <failure type="java.lang.AssertionError" message="expected [20] but found [40]">
      <![CDATA[java.lang.AssertionError: expected [20] but found [40]
at Dwopractice1.NewTest.testCase5(NewTest.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testCase5 -->
  <testcase classname="Dwopractice1.NewTest" name="testCase6" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [40] but found [60]">
      <![CDATA[java.lang.AssertionError: expected [40] but found [60]
at Dwopractice1.NewTest.testCase6(NewTest.java:71)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testCase6 -->
  <testcase classname="Dwopractice1.NewTest" name="testCase7" time="0.016">
    <failure type="java.lang.AssertionError" message="expected [50] but found [25]">
      <![CDATA[java.lang.AssertionError: expected [50] but found [25]
at Dwopractice1.NewTest.testCase7(NewTest.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testCase7 -->
  <testcase classname="Dwopractice1.NewTest" name="testCase8" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [80] but found [70]">
      <![CDATA[java.lang.AssertionError: expected [80] but found [70]
at Dwopractice1.NewTest.testCase8(NewTest.java:93)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testCase8 -->
  <testcase classname="Dwopractice1.NewTest" name="testCase9" time="0.011">
    <skipped/>
  </testcase> <!-- testCase9 -->
  <testcase classname="Dwopractice1.NewTest" name="testCase10" time="0.003">
    <skipped/>
  </testcase> <!-- testCase10 -->
</testsuite> <!-- Test -->
